baseURL = 'https://vincent-tarrit-veiltech.github.io/'
languageCode = 'fr-ch'
title = 'Vincent Tarrit - VeilTech'
theme = "hugo-digital-garden-theme"
themesdir = "./themes"

[params]
  name = "La tech de Vincent"
  description = " "
  initials = "VT"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/TarritVincent"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/vincent-tarrit"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/vincent-tarrit/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2


[taxonomies]
  blog_tags = 'blog_tags'
  


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'