baseURL = 'https://vincent-tarrit-veiltech.github.io/'
languageCode = 'en-us'
title = 'Vincent Tarrit - VeilTech'
theme = "papermod"
publishdir = "docs"

menu = [
  { name = "Home", url = "/", weight = 1 },
  { name = "About", url = "/about/", weight = 2 },
  { name = "Posts", url = "/posts/", weight = 3 },
  { name = "Contact", url = "/contact/", weight = 4 },
]